/**
 * WHERE THE KIT IS ALLOWED TO ATTACH A TRACE HEADER.
 *
 * The kit already stands inside the host's outgoing HTTP call — it is holding
 * the request object to measure it. Attaching the three trace headers while it
 * is there is what turns a collection of single-service traces into one chain.
 *
 * But an outgoing call is not necessarily a call to another part of the
 * customer's own system. It may be a payment provider, a model vendor, a
 * webhook, an analytics endpoint. Attaching a header there means an outside
 * company receives an identifier generated by Boosthis, on a request Boosthis
 * had no business modifying, and the customer never asked for that and cannot
 * see it happening.
 *
 * So propagation is DECIDED, not assumed, and the decision is made from the
 * destination host alone:
 *
 *   • The default permits only destinations that CANNOT be on the public
 *     internet — loopback, the private and carrier-grade IPv4 ranges, IPv6
 *     unique-local, a single-label container/service name, and the hostname
 *     suffixes reserved for private use. An outside company is reachable at a
 *     public name on a public address, so under the default it never receives
 *     the header.
 *   • A customer who runs their own services on public DNS widens it by naming
 *     hosts or suffixes. What they name is what they get: the list REPLACES the
 *     default rather than extending it, because "these destinations" is the
 *     only reading of an explicit list that cannot surprise anyone.
 *   • `none` switches propagation off entirely, and wins over anything else in
 *     the same list. The most restrictive entry always decides.
 *
 * TWO DELIBERATE EXCLUSIONS FROM THE DEFAULT SET, both for the same reason —
 * the address is private but the machine answering is somebody else's:
 *
 *   • IPv4 link-local `169.254.0.0/16` and IPv6 `fe80::/10`. `169.254.169.254`
 *     is the cloud provider's instance-metadata service on every major host.
 *     It is not the customer's service and it is not ours to tag.
 *   • There is no `all` keyword. A switch that means "send our identifier to
 *     every destination this app talks to" is a promise we could not make in
 *     the published disclosure, so it does not exist. A customer who wants a
 *     public destination names it.
 *
 * The module is PURE and allocation-cheap: no I/O, no imports beyond the header
 * names, no regular expression run per call. It is consulted once per outgoing
 * request on the host's own stack, so the whole judgement is a lowercase, a
 * handful of character comparisons and at most one pass over a short list.
 *
 * Byte-parity: `boosthis/trace_propagation.py` in the Python kit implements the
 * same rule with the same constants, and
 * `scripts/src/__tests__/trace-propagation-parity.test.ts` holds the two to
 * each other and to the written coverage record.
 */

/** The one setting. Unset means {@link DEFAULT_PROPAGATION}. */
export const PROPAGATION_ENV = "BOOSTHIS_TRACE_PROPAGATION";

/** What an unset {@link PROPAGATION_ENV} means. */
export const DEFAULT_PROPAGATION = "internal";

/** The keyword for the built-in "cannot be on the public internet" set. */
export const INTERNAL_KEYWORD = "internal";

/** The keywords that switch propagation off. Either spelling, because both
 *  are what people type, and a setting that silently ignores the customer's
 *  attempt to turn something off is the worst kind of setting. */
export const OFF_KEYWORDS: readonly string[] = ["none", "off"];

/** Hostname suffixes reserved for private/internal use. A name ending in one
 *  of these cannot resolve to an outside company's service. Each is matched as
 *  the whole host or as a dot-preceded suffix of it, so `.local` covers
 *  `api.local` and Kubernetes' `svc.cluster.local` alike. */
export const INTERNAL_SUFFIXES: readonly string[] = [
  "localhost",
  "local",
  "internal",
  "intranet",
  "home.arpa",
  "lan",
  "test",
];

/** Single-label names that DO have a public DNS answer, against the rule
 *  below that reads a dotless name as a container or Kubernetes short name.
 *  That reading is right almost always and wrong for a handful of top-level
 *  domains which carry address records of their own: `ws`, `tk` and `uz`
 *  answer publicly today, so under the default `http://ws/` would leave the
 *  building carrying an identifier we generated. The rest have answered
 *  within living memory and can again.
 *
 *  A denylist rather than the full list of registered top-level domains, on
 *  purpose: `dev`, `app`, `cloud` and `zone` are all real TLDs AND thoroughly
 *  ordinary internal service names, so refusing every registered TLD would
 *  refuse the common case in order to close the rare one.
 *
 *  Matched as the WHOLE host, lowercased, and only against the built-in set —
 *  a customer whose own service really is called `ws` names it in their list
 *  and that is a recorded decision this module does not overrule.
 *
 *  Source: the dotless-domain surveys behind ICANN SAC053. Re-checked
 *  2026-09-10. Being a superset of what resolves today is the conservative
 *  direction: a name that stops resolving costs a customer one list entry. */
export const PUBLIC_DOTLESS_HOSTS: readonly string[] = [
  "ac",
  "ai",
  "cm",
  "dk",
  "gg",
  "hr",
  "io",
  "je",
  "kh",
  "kw",
  "mq",
  "pa",
  "ph",
  "pn",
  "sh",
  "sj",
  "su",
  "tk",
  "tm",
  "to",
  "ua",
  "uz",
  "va",
  "ws",
];

/** Destinations that live INSIDE the set above but belong to the hosting
 *  provider rather than to the customer. Each is reachable at a name or an
 *  address the built-in set calls internal — `metadata.google.internal` ends
 *  in a reserved suffix, `metadata` is a single label, AWS's IPv6 instance
 *  metadata service is a unique-local address, Alibaba's sits inside CGNAT —
 *  so without this list the default would put a Boosthis identifier in a
 *  request to infrastructure the customer does not own. That is the very
 *  thing excluding link-local was for, and excluding link-local alone did not
 *  achieve it.
 *
 *  Matched as the WHOLE host, lowercased. It applies only to the built-in
 *  set: a customer who names one of these in their own list has made a
 *  recorded decision, and this module does not overrule it.
 *
 *  It cannot be complete — a provider can add an endpoint tomorrow. It closes
 *  the published ones, and the numeric forms below close the addresses. */
export const PROVIDER_METADATA_HOSTS: readonly string[] = [
  "metadata", // Google Cloud, the short alias
  "metadata.google.internal", // Google Cloud
  "metadata.goog", // Google Cloud
  "metadata.internal", // several providers' short form
  "instance-data", // AWS, the documented alias for the IMDS
  "instance-data.ec2.internal", // AWS
];

/** The same services at their fixed ADDRESSES. Written here as text and
 *  compared as numbers, because `fd00:0ec2::254` is `fd00:ec2::254` written
 *  out and `0100.0144.0144.0310` is Alibaba's in octal — a string test would
 *  catch one spelling of each. */
export const PROVIDER_METADATA_ADDRESSES: readonly string[] = [
  "169.254.169.254", // AWS, Azure, Google Cloud, Oracle, DigitalOcean
  "100.100.100.200", // Alibaba Cloud — inside CGNAT, which the set permits
  "192.0.0.192", // Oracle Cloud Classic
  "fd00:ec2::254", // AWS over IPv6 — a unique-local address
];

/** How many entries a customer's list may contain before the rest are refused.
 *  A bounded list keeps the per-call judgement bounded; a customer who needs
 *  more than this wants a suffix, not another hundred hosts. */
export const MAX_PROPAGATION_ENTRIES = 64;

/** What the customer asked for, in a shape a surface can render. */
export interface PropagationPolicy {
  /** True when nothing is ever attached. */
  readonly off: boolean;
  /** True when the built-in non-public set is permitted. */
  readonly internal: boolean;
  /** Exact hostnames the customer named, lowercased, in the order given. */
  readonly hosts: readonly string[];
  /** Suffixes the customer named, WITHOUT the leading dot, in the order given. */
  readonly suffixes: readonly string[];
  /** Entries that were not a bare host or a leading-dot suffix, kept so the
   *  surface can say a typo was ignored rather than silently obeying half a
   *  list. Capped, like the list itself. */
  readonly refused: readonly string[];
  /** True when the setting was absent or empty, so this is the default. */
  readonly isDefault: boolean;
}

/** The policy that applies when nobody has said anything. */
const DEFAULT_POLICY: PropagationPolicy = Object.freeze({
  off: false,
  internal: true,
  hosts: Object.freeze([]) as readonly string[],
  suffixes: Object.freeze([]) as readonly string[],
  refused: Object.freeze([]) as readonly string[],
  isDefault: true,
});

/** Nothing is attached, anywhere. Used for an explicit `none` and as the
 *  fail-safe when reading the setting throws. */
const OFF_POLICY: PropagationPolicy = Object.freeze({
  off: true,
  internal: false,
  hosts: Object.freeze([]) as readonly string[],
  suffixes: Object.freeze([]) as readonly string[],
  refused: Object.freeze([]) as readonly string[],
  isDefault: false,
});

/** A host label is what a hostname may contain. Deliberately strict: anything
 *  with a scheme, a port, a path, a wildcard or whitespace is a mistake, and a
 *  mistake that is obeyed approximately is worse than one that is refused. */
function looksLikeHost(value: string): boolean {
  if (value.length === 0 || value.length > 253) return false;
  for (let i = 0; i < value.length; i++) {
    const c = value.charCodeAt(i);
    const ok =
      (c >= 97 && c <= 122) || // a-z
      (c >= 48 && c <= 57) || // 0-9
      c === 45 || // -
      c === 46 || // .
      c === 58; // : — an IPv6 literal, which a customer may legitimately name
    if (!ok) return false;
  }
  return true;
}

/**
 * Read one setting value into a policy. Exported for the parity guard and the
 * tests; the running kit goes through {@link tracePropagationPolicy}.
 *
 * Never throws. An unreadable or nonsense value degrades to the DEFAULT, not
 * to "everything": the failure mode of a misread setting must be the
 * conservative one.
 */
export function parseTracePropagation(raw: unknown): PropagationPolicy {
  if (raw === undefined || raw === null) return DEFAULT_POLICY;
  const text = String(raw).trim();
  if (text.length === 0) return DEFAULT_POLICY;

  let internal = false;
  const hosts: string[] = [];
  const suffixes: string[] = [];
  const refused: string[] = [];
  let seen = 0;

  for (const piece of text.split(",")) {
    const entry = piece.trim().toLowerCase();
    if (entry.length === 0) continue;
    // The most restrictive entry decides, wherever it appears in the list. A
    // customer who wrote `none` meant it, even if they left older entries
    // beside it.
    if (OFF_KEYWORDS.includes(entry)) return OFF_POLICY;
    if (++seen > MAX_PROPAGATION_ENTRIES) {
      if (refused.length < MAX_PROPAGATION_ENTRIES) refused.push(entry);
      continue;
    }
    if (entry === INTERNAL_KEYWORD) {
      internal = true;
      continue;
    }
    if (entry.startsWith(".")) {
      const suffix = entry.slice(1);
      if (suffix.length > 0 && looksLikeHost(suffix)) suffixes.push(suffix);
      else refused.push(entry);
      continue;
    }
    if (looksLikeHost(entry)) hosts.push(entry);
    else refused.push(entry);
  }

  // A list of nothing but refusals is a list the customer meant to widen
  // something with. Falling back to the default is right — it is what they had
  // before they typed it — and the refused entries are on the surface so they
  // can see why nothing changed.
  if (!internal && hosts.length === 0 && suffixes.length === 0) {
    return Object.freeze({
      off: false,
      internal: true,
      hosts: Object.freeze([]) as readonly string[],
      suffixes: Object.freeze([]) as readonly string[],
      refused: Object.freeze(refused) as readonly string[],
      isDefault: true,
    });
  }

  return Object.freeze({
    off: false,
    internal,
    hosts: Object.freeze(hosts) as readonly string[],
    suffixes: Object.freeze(suffixes) as readonly string[],
    refused: Object.freeze(refused) as readonly string[],
    isDefault: false,
  });
}

let cached: PropagationPolicy | null = null;

/** The policy in force, read from the environment once and remembered. The
 *  setting is read at most once per process because this sits on the host's
 *  outgoing-call path, and a `process.env` read there is a cost the host did
 *  not ask for. Never throws. */
export function tracePropagationPolicy(): PropagationPolicy {
  if (cached !== null) return cached;
  try {
    cached = parseTracePropagation(process.env[PROPAGATION_ENV]);
  } catch {
    // A host that has made `process.env` unreadable gets the fail-safe answer,
    // not the permissive one.
    cached = OFF_POLICY;
  }
  return cached;
}

/** Forget the remembered policy. For tests, and for an app that changes the
 *  setting after start-up and wants it re-read. */
export function resetTracePropagationPolicy(): void {
  cached = null;
}

/** True when `host` is an IPv4 dotted quad, filling `out` with its octets. */
/**
 * True when a RESOLVER will read `host` as a number rather than as a name.
 *
 * `inet_aton` — which is what the resolver ends up using — accepts one to four
 * dot-separated parts, each written in decimal, octal (a leading zero) or
 * hexadecimal (a leading `0x`). So `010.010.010.010` and `134744072` and
 * `0x8.0x8.0x8.0x8` are all 8.8.8.8, and `2852039166` is the cloud metadata
 * address. Only a part that is not a number in any of those bases makes the
 * whole thing a name.
 */
function isNumericAddressForm(host: string): boolean {
  const parts = host.split(".");
  if (parts.length < 1 || parts.length > 4) return false;
  for (const part of parts) {
    const hexed = part.slice(0, 2) === "0x" || part.slice(0, 2) === "0X";
    const body = hexed ? part.slice(2) : part;
    if (body.length === 0) return false;
    for (let i = 0; i < body.length; i++) {
      const c = body.charCodeAt(i);
      const dec = c >= 48 && c <= 57;
      const hex =
        hexed && ((c >= 97 && c <= 102) || (c >= 65 && c <= 70));
      if (!dec && !hex) return false;
    }
  }
  return true;
}

/**
 * Parse a dotted quad in its ONE canonical spelling.
 *
 * Strict on purpose: exactly four parts, ASCII decimal, and no leading zero on
 * a longer part. Every other numeric spelling of an address is refused by
 * `isInternalHost` rather than canonicalised here, because the only safe rule
 * is that the address the resolver reaches is the address this judged.
 */
function readIPv4(host: string, out: number[]): boolean {
  const parts = host.split(".");
  if (parts.length !== 4) return false;
  for (let i = 0; i < 4; i++) {
    const part = parts[i] as string;
    if (part.length === 0 || part.length > 3) return false;
    // A leading zero is octal to the resolver and decimal to us.
    if (part.length > 1 && part.charCodeAt(0) === 48) return false;
    let value = 0;
    for (let j = 0; j < part.length; j++) {
      const c = part.charCodeAt(j);
      if (c < 48 || c > 57) return false;
      value = value * 10 + (c - 48);
    }
    if (value > 255) return false;
    out[i] = value;
  }
  return true;
}

/** Read ONE IPv6 group as a number, or -1. Used to compare an address rather
 *  than its spelling: `fd00:0ec2::254` and `fd00:ec2::254` are the same
 *  address, and a string test would catch only one of them. */
function readHexGroup(text: string | undefined): number {
  if (typeof text !== "string" || text.length === 0 || text.length > 4) {
    return -1;
  }
  let value = 0;
  for (let i = 0; i < text.length; i++) {
    const c = text.charCodeAt(i);
    let digit: number;
    if (c >= 48 && c <= 57) digit = c - 48;
    else if (c >= 97 && c <= 102) digit = c - 87;
    else if (c >= 65 && c <= 70) digit = c - 55;
    else return -1;
    value = value * 16 + digit;
  }
  return value;
}

/**
 * True when `host` is a hosting provider's instance metadata service.
 *
 * Checked BEFORE the built-in set, and only against it. See
 * {@link PROVIDER_METADATA_HOSTS} for why: these destinations sit inside the
 * private ranges by design, so the set that means "cannot be an outside
 * company" would otherwise permit them.
 *
 * The cost is stated rather than hidden: a customer whose own service is
 * genuinely called `metadata` loses propagation to it under the default and
 * has to name it in their list. That is the safe direction.
 */
export function isProviderMetadataHost(host: string): boolean {
  if (host.length === 0) return false;
  const bare = host.charCodeAt(0) === 91 /* [ */
    ? host.slice(1, host.endsWith("]") ? -1 : undefined)
    : host;

  for (const name of PROVIDER_METADATA_HOSTS) {
    if (bare === name) return true;
  }

  if (bare.includes(":")) {
    // Only the first two groups are compared, so the whole of `fd00:ec2::/32`
    // is refused rather than one address in it. They can never be elided: an
    // address that starts with `::` has zeros there and is not one of these.
    const groups = bare.split(":");
    const first = readHexGroup(groups[0]);
    const second = readHexGroup(groups[1]);
    if (first < 0 || second < 0) return false;
    for (const listed of PROVIDER_METADATA_ADDRESSES) {
      if (!listed.includes(":")) continue;
      const parts = listed.split(":");
      if (readHexGroup(parts[0]) === first && readHexGroup(parts[1]) === second) {
        return true;
      }
    }
    return false;
  }

  const quad: number[] = [0, 0, 0, 0];
  if (!readIPv4(bare, quad)) return false;
  const listed: number[] = [0, 0, 0, 0];
  for (const address of PROVIDER_METADATA_ADDRESSES) {
    if (address.includes(":")) continue;
    if (!readIPv4(address, listed)) continue;
    if (
      quad[0] === listed[0] &&
      quad[1] === listed[1] &&
      quad[2] === listed[2] &&
      quad[3] === listed[3]
    ) {
      return true;
    }
  }
  // The built-in set already excludes all of 169.254.0.0/16, where five
  // providers answer. The reason lives here too, so a later widening of that
  // range cannot reopen this door by accident.
  return quad[0] === 169 && quad[1] === 254;
}

/**
 * True when `host` cannot be an outside company's service — the built-in
 * default set.
 *
 * Exported because the coverage record and the surface both quote it, and a
 * rule the customer is shown must be the rule that runs.
 */
export function isInternalHost(host: string): boolean {
  if (host.length === 0) return false;

  // THE HOSTING PROVIDER IS NOT THE CUSTOMER. Decided first, because every
  // one of these destinations would pass one of the rules below.
  if (isProviderMetadataHost(host)) return false;

  // IPv6, with or without the brackets an origin carries.
  if (host.charCodeAt(0) === 91 /* [ */ || host.includes(":")) {
    const bare = host.startsWith("[")
      ? host.slice(1, host.endsWith("]") ? -1 : undefined)
      : host;
    if (bare === "::1") return true;
    // Unique-local fc00::/7 — the FIRST BYTE is 0xfc or 0xfd, which in text
    // means a first group of exactly four hex digits beginning fc or fd. The
    // length test is the whole point: `fce:1234::1` also begins "fc", but its
    // first group is three digits, so the first byte is 0x0f and the address
    // is public. A prefix test alone would have handed a stranger the header.
    if (bare.indexOf(":") === 4) {
      const lead = bare.slice(0, 2);
      if (lead === "fc" || lead === "fd") {
        const c = bare.charCodeAt(2);
        const d = bare.charCodeAt(3);
        const hex = (n: number): boolean =>
          (n >= 48 && n <= 57) || (n >= 97 && n <= 102);
        if (hex(c) && hex(d)) return true;
      }
    }
    // fe80::/10 (link-local) is deliberately NOT here — see the module note.
    return false;
  }

  const quad: number[] = [0, 0, 0, 0];
  if (readIPv4(host, quad)) {
    const a = quad[0] as number;
    const b = quad[1] as number;
    if (a === 127) return true; // loopback 127.0.0.0/8
    if (a === 10) return true; // private 10.0.0.0/8
    if (a === 172 && b >= 16 && b <= 31) return true; // private 172.16.0.0/12
    if (a === 192 && b === 168) return true; // private 192.168.0.0/16
    if (a === 100 && b >= 64 && b <= 127) return true; // CGNAT 100.64.0.0/10
    // 169.254.0.0/16 is deliberately NOT here — see the module note.
    return false;
  }

  // A NUMERIC SPELLING WE DID NOT READ OURSELVES. `010.010.010.010` is octal
  // to the resolver and reaches 8.8.8.8; `134744072` and `0x08080808` reach it
  // too; `2852039166` reaches the metadata service. To the name-shaped tests
  // below, the last three look like single-label hostnames, which this set
  // calls internal — so a public address would be permitted under the default.
  // Refusing every numeric form the strict reader above declined is the only
  // answer that cannot disagree with the resolver.
  if (isNumericAddressForm(host)) return false;

  // A single-label name is a Docker Compose service, a Kubernetes short name,
  // an /etc/hosts entry — EXCEPT for the top-level domains that carry address
  // records of their own. Those resolve for anyone, so reading every dotless
  // name as internal would carry the header to a stranger.
  if (!host.includes(".")) {
    for (const dotless of PUBLIC_DOTLESS_HOSTS) {
      if (host === dotless) return false;
    }
    return true;
  }

  for (const suffix of INTERNAL_SUFFIXES) {
    if (host === suffix) return true;
    if (host.length > suffix.length + 1 && host.endsWith(`.${suffix}`)) {
      return true;
    }
  }
  return false;
}

/** Decide whether the trace headers may be attached to a call to `host`.
 *
 * `host` is the bare hostname — no scheme, no port, no path, no userinfo. It
 * never leaves this stack: the answer is a boolean, and nothing about the
 * destination is recorded, counted or uploaded by this module.
 *
 * Never throws. Anything it cannot judge is a refusal. */
export function shouldPropagateTo(host: unknown): boolean {
  try {
    if (typeof host !== "string" || host.length === 0) return false;
    const policy = tracePropagationPolicy();
    if (policy.off) return false;
    const lower = host.toLowerCase();
    if (policy.internal && isInternalHost(lower)) return true;
    for (const named of policy.hosts) {
      if (lower === named) return true;
    }
    for (const suffix of policy.suffixes) {
      if (lower === suffix) return true;
      if (lower.length > suffix.length + 1 && lower.endsWith(`.${suffix}`)) {
        return true;
      }
    }
    return false;
  } catch {
    return false;
  }
}

/** What a customer surface shows: the rule in force, in the customer's own
 *  terms, with no host of theirs invented and none of ours assumed. */
export interface PropagationDescription {
  /** `off`, `internal` (the default set only), or `named`. */
  readonly mode: "off" | "internal" | "named";
  /** True when the built-in non-public set is part of what is permitted. */
  readonly internal: boolean;
  /** The destinations the customer named, rendered back the way they wrote
   *  them — a suffix keeps its leading dot. */
  readonly named: readonly string[];
  /** Entries that were not usable and were ignored. */
  readonly refused: readonly string[];
  /** The setting's name, so a surface never hard-codes it. */
  readonly setting: string;
}

/** Describe the policy in force for a customer-facing surface. Never throws. */
export function describeTracePropagation(): PropagationDescription {
  let policy: PropagationPolicy;
  try {
    policy = tracePropagationPolicy();
  } catch {
    policy = OFF_POLICY;
  }
  const named = [
    ...policy.hosts,
    ...policy.suffixes.map((suffix) => `.${suffix}`),
  ];
  return {
    mode: policy.off ? "off" : named.length > 0 ? "named" : "internal",
    internal: policy.internal,
    named,
    refused: policy.refused,
    setting: PROPAGATION_ENV,
  };
}

/** How many named destinations a one-line summary spells out before it stops
 *  counting. A status row is one line; a customer with forty entries needs the
 *  shape of the answer, not the list. */
const SUMMARY_NAMED_LIMIT = 4;

/**
 * ONE SENTENCE SAYING WHERE THE TRACE IS BEING PASSED ON.
 *
 * The customer-visible answer to "is this happening, and to whom?", so the
 * behaviour is inspectable rather than implicit. Rendered by the kit's status
 * page; the Python kit's `trace_propagation_summary` produces the same words
 * from the same policy, and the two are held to each other by
 * `scripts/src/__tests__/trace-propagation-parity.test.ts`.
 *
 * NAMES ONLY WHAT THE CUSTOMER TYPED. The built-in set is described in words
 * rather than listed, because it is a rule about addresses, not a list of
 * hosts — and because a kit that printed the hosts it had decided were
 * internal would be printing the app's own topology onto a page. Never raises.
 */
export function tracePropagationSummary(): string {
  let d: PropagationDescription;
  try {
    d = describeTracePropagation();
  } catch {
    return "Off — no trace headers are attached to outgoing calls";
  }
  const ignored =
    d.refused.length > 0
      ? ` (ignored, not a hostname: ${d.refused.slice(0, SUMMARY_NAMED_LIMIT).join(", ")}` +
        `${d.refused.length > SUMMARY_NAMED_LIMIT ? ", …" : ""})`
      : "";
  if (d.mode === "off") {
    return `Off — no trace headers are attached to outgoing calls${ignored}`;
  }
  const shown = d.named.slice(0, SUMMARY_NAMED_LIMIT).join(", ");
  const more =
    d.named.length > SUMMARY_NAMED_LIMIT
      ? ` and ${d.named.length - SUMMARY_NAMED_LIMIT} more`
      : "";
  if (d.mode === "internal") {
    return `Internal destinations only — the default${ignored}`;
  }
  if (d.internal) {
    return `Internal destinations, plus ${shown}${more}${ignored}`;
  }
  return `Only ${shown}${more}${ignored}`;
}
